"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { ResumeEditor } from "@/components/resume-editor"
import { InterviewQuestions } from "@/components/interview-questions"
import { ApplicationLogger } from "@/components/application-logger"
import { useRouter } from "next/navigation"
import { useToast } from "@/hooks/use-toast"

export default function CreateResume() {
  const [jobDescription, setJobDescription] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [resumeGenerated, setResumeGenerated] = useState(false)
  const router = useRouter()
  const { toast } = useToast()

  // Mock resume data that would be generated by AI
  const mockResumeData = {
    personalInfo: {
      name: "Alex Johnson",
      email: "alex.johnson@example.com",
      phone: "(555) 123-4567",
      location: "San Francisco, CA",
      linkedin: "linkedin.com/in/alexjohnson",
    },
    summary:
      "Experienced software engineer with 5+ years of expertise in full-stack development, specializing in React, Node.js, and cloud technologies. Proven track record of delivering scalable applications and optimizing performance.",
    experience: [
      {
        title: "Senior Software Engineer",
        company: "Tech Innovations Inc.",
        location: "San Francisco, CA",
        startDate: "Jan 2021",
        endDate: "Present",
        highlights: [
          "Led development of a microservices architecture that improved system reliability by 40%",
          "Implemented CI/CD pipelines reducing deployment time by 60%",
          "Mentored junior developers and conducted code reviews",
        ],
      },
      {
        title: "Software Engineer",
        company: "Digital Solutions LLC",
        location: "San Francisco, CA",
        startDate: "Jun 2018",
        endDate: "Dec 2020",
        highlights: [
          "Developed RESTful APIs serving 1M+ daily requests",
          "Optimized database queries resulting in 30% performance improvement",
          "Collaborated with UX team to implement responsive designs",
        ],
      },
    ],
    education: [
      {
        degree: "M.S. Computer Science",
        institution: "Stanford University",
        location: "Stanford, CA",
        graduationDate: "2018",
      },
      {
        degree: "B.S. Computer Science",
        institution: "University of California, Berkeley",
        location: "Berkeley, CA",
        graduationDate: "2016",
      },
    ],
    skills: [
      "JavaScript/TypeScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "PostgreSQL",
      "AWS",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Git",
      "Agile/Scrum",
    ],
  }

  const handleGenerateResume = () => {
    if (!jobDescription.trim()) {
      toast({
        title: "Error",
        description: "Please enter a job description",
        variant: "destructive",
      })
      return
    }

    setIsGenerating(true)

    // Simulate API call delay
    setTimeout(() => {
      setIsGenerating(false)
      setResumeGenerated(true)
      toast({
        title: "Success",
        description: "Resume generated successfully",
      })
    }, 2000)
  }

  return (
    <div className="container py-10">
      <div className="mb-6">
        <h1 className="text-3xl font-bold mb-2">Create Tailored Resume</h1>
        <p className="text-muted-foreground">Enter a job description to generate an ATS-optimized resume</p>
      </div>

      <ApplicationLogger />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Column - Input */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Job Description</CardTitle>
              <CardDescription>Paste the job description to tailor your resume</CardDescription>
            </CardHeader>
            <CardContent>
              <Textarea
                placeholder="Paste job description here..."
                className="min-h-[300px]"
                value={jobDescription}
                onChange={(e) => setJobDescription(e.target.value)}
              />
            </CardContent>
            <CardFooter>
              <Button onClick={handleGenerateResume} disabled={isGenerating} className="ml-auto">
                {isGenerating ? "Generating..." : "Generate Resume"}
              </Button>
            </CardFooter>
          </Card>
        </div>

        {/* Right Column - Output */}
        <div>
          {resumeGenerated ? (
            <Tabs defaultValue="resume" className="w-full">
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="resume">Resume</TabsTrigger>
                <TabsTrigger value="interview">Interview Prep</TabsTrigger>
              </TabsList>
              <TabsContent value="resume">
                <ResumeEditor resumeData={mockResumeData} />
              </TabsContent>
              <TabsContent value="interview">
                <InterviewQuestions jobDescription={jobDescription} />
              </TabsContent>
            </Tabs>
          ) : (
            <Card className="h-full flex items-center justify-center min-h-[300px]">
              <CardContent className="text-center text-muted-foreground">
                <p>Enter a job description and click "Generate Resume" to create your tailored resume.</p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  )
}
